version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image:  krishnap1999/video-streaming-platform/frontend:latest
    hostname: www.surajzinzuwadia.com
    ports:
      - 3000:3000
    # volumes:
    #   - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
      - database
    networks:
      - my_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: krishnap1999/video-streaming-platform/backend:latest
    ports:
      - 8001:8000
    volumes:
      - ssl_certs_volume:/app/certs
    environment:
      - NODE_ENV=development
    depends_on:
      - database
    networks:
      - my_network
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: krishnap1999/video-streaming-platform/database:latest
    ports:
      - 3001:3001
    # volumes:
    #   - ./database:/app
    environment:
      - NODE_ENV=development
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge

volumes:
  ssl_certs_volume:
    external: true