version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image:  krishnap1999/video-streaming-platform/frontend:latest
    ports:
      - 3000:3000
    # volumes:
    #   - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  backend:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: krishnap1999/video-streaming-platform/backend:latest
    ports:
      - 3001:3001
    # volumes:
    #   - ./database:/app
    environment:
      - NODE_ENV=development